[JSTesting] partial rewrite of TestSwarmMWFetcher * Before rewrite (should've been a separate commit) -- Removing savedPath/chdir code (unused). We probably shouldn't be changing paths. If need to execute commands on paths outside our current working directory we can provide relative or absolute paths to those functions. -- Removing getFirstRev, using minRev directly. --  Fix bug in __construct (using || instead of && to verify required options) --  Fix bug in getNextFollowingRevId, distinguish between invalid id and no id at all. Return null if there is no next id (given id is >= HEAD) --  Fix bug in log(); Call fclose() on the handle, not the file path. Pass handle as first argument to fwrite(), instead of file path as second argument.
* During/after ewrite:
-- Creating separate class for the install process so we have a context for stuff like paths and revision ids (instead of passing around everything all the time).
-- Removing getLogFile(). Instead putting the full path directly in getPaths()
-- Changing log path from /log/r123/debug.log to /logs/r123.log
-- Renaming variables and functions to make a clearer distinction between the local checkout and the remote repo (i.e. "getNextRev")
-- Changing order of functions. Defining functions in order of usage (and before they are used - where possible).

* Follows-up r101636

--

Right now it successfully does the checkout and installing of the wiki.
@todo:
- Append settings template to LocalSettings
- Append require() for global settings to LocalSettings
- TestSwarm job submitter (needs config for testswarm instance location)
- After running preprod-mode, got error:

Location: http://localhost/mw/trunk/tools/testswarm/scripts/_checkouts_symlink/r101591/

A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: http://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: DELETE FROM msg_resource
Function: MessageBlobStore::clear
Error: 8 attempt to write a readonly database

git-svn-id: svn+ssh://svn.wikimedia.org/svnroot/mediawiki/trunk@101744 dd0e9695-b195-4be7-bd10-2dea1a65a6b6